name: Test
on:
  push:


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:

    - name: Write secrets
      env:
        secrets_config: |
          [together]
          api_key = "${{ secrets.ONE }}"

          [openai]
          api_key = "${{ secrets.TWO }}"
      run: |
        mkdir -p config
        echo $SECRETS_CONFIG > config/secrets.toml
      
    - name: show secrets
      run: cat config/secrets.toml
